# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux 
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: /scripts/ApplicationStop.sh
      timeout: 10
      runas: root
  BeforeInstall:
    - location: /scripts/BeforeInstall.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: /scripts/AfterInstall.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: /scripts/ApplicationStart.sh
      timeout: 10
      runas: root
  ValidateService:
    - location: /scripts/ApplicationStart.sh
      timeout: 10
      runas: root
