# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux 
files:
  - source: index.html
    destination: /var/www/html/
  - source: scripts/*
    destination: scripts/
hooks:
  ApplicationStop:
    - location: ApplicationStop.sh
      timeout: 10
      runas: root
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 10
      runas: root
  ValidateService:
    - location: ApplicationStart.sh
      timeout: 10
      runas: root
